HPC-8672: Change how latest published reporting period is calculated
UN-OCHA/hpc-api pull request #160
Opened 2023-03-22 15:49 UTC by Pl217

Instead of just taking the highest plan reporting period that has measurements generated, first find if any of the newly published reporting periods are higher than currently stored `lastPublishedReportingPeriodId`.

This way, we ensure that first time publishing of reporting periods using custom publishing actually updates the plan version and its `lastPublishedReportingPeriodId` field.

2023-03-22 16:05 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2023-03-23 10:31 UTC, krishnareddy-tadi requested changes

2023-03-23 10:31 UTC, krishnareddy-tadi commented on src/common-libs/plan/index.ts
> +  }
We can replace for loop with below 
```suggestion
 const maxRemainingPeriod = remainingPeriods.reduce((p, c) =>
    p.periodNumber ?? -1 > (c.periodNumber ?? -1) ? p : c
  );
  if (
    (maxRemainingPeriod.periodNumber ?? -1) >
    (latestPublishedReportingPeriod.periodNumber ?? -1)
  ) {
    latestPublishedReportingPeriod = maxRemainingPeriod;
  }
```

2023-03-23 13:46 UTC, Pl217 commented on src/common-libs/plan/index.ts
> +  }
Actually, we can find `latestPublishedReportingPeriod` with a single `Array.prototype.reduce()` call and avoid `for..of` loop, but also avoid finding the first and `remainingPeriods`:
```typescript
const latestPublishedReportingPeriod = reportingPeriods.reduce((acc, curr) =>
  (curr.periodNumber ?? -1) > (acc.periodNumber ?? -1) ? curr : acc
);
```

2023-03-23 13:47 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2023-03-23 14:22 UTC, krishnareddy-tadi approved these changes

2023-03-23 14:41 UTC, merged