[OPS-8820] remove NewRelic
UN-OCHA/hpc-api pull request #168
Opened 2023-04-03 09:46 UTC by teodorescuserban

2023-04-03 17:28 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2023-04-04 14:09 UTC, Pl217 requested changes
I don't yet know whether we want/need to remove NewRelic from APIs as well. Waiting for an answer on [this Jira comment](https://humanitarian.atlassian.net/browse/OPS-8820?focusedCommentId=149446).

2023-04-04 14:09 UTC, Pl217 commented on src/server.ts
> -if (process.env.NEW_RELIC_LICENSE_KEY) {
`NEW_RELIC_LICENSE_KEY` is appearing in two `docker-compose.yml` files. You should remove it from there too.

2023-04-04 15:09 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2023-04-04 15:09 UTC, Pl217 approved these changes

2023-04-04 15:11 UTC, merged