HPC-7811 set up test environment
UN-OCHA/hpc-api pull request #217
Opened 2023-10-26 08:55 UTC by manelcecs

This PR aims to add Jest test environment for HPC-API
Also provide a set of initial test for GraphQL

2023-10-26 09:04 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2023-11-09 11:40 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2023-11-10 11:05 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2023-11-17 14:21 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2024-01-14 16:08 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2024-03-19 20:34 UTC, Pl217 requested changes
I have rebased this PR and resolved issues I write about inline. All except the comment about undefined variable `$STOP` and option `-ns`, which don't exist, but are mentioned in `bin/test.sh`.

Also, I have made the following changes:
- Set up CI to run unit tests
- Changed Solr config to latest one
- Use newest DB migration file

2024-03-19 20:34 UTC, Pl217 commented on bin/test.sh
> +STOP_CONTAINERSq=0
Unused and has weird "q" at the end
```suggestion
```

2024-03-19 20:34 UTC, Pl217 commented on bin/test.sh
> +    echo "$usage"
This variable is named with all uppercases:
```suggestion
    echo "$USAGE"
```

2024-03-19 20:34 UTC, Pl217 commented on bin/test.sh
> +    echo 'Invalid options - when using option -oc, option -ns must be used as well'
Variable `$STOP` doesn't exist. Also, option `ns` that you mention in error message doesn't exist too.

2024-03-19 20:34 UTC, Pl217 commented on tests/docker-compose.yml
> +    container_name: test_hidservice_test_api
The HID API mock service doesn't even exist in this repo

2024-03-19 20:34 UTC, Pl217 commented on tests/docker-compose.yml
> +      - '../data/test/hpc/solr_backups:/var/solr/data/backups:rw'
We don't need to be concerned with Solr backups for test containers.

2024-03-19 20:34 UTC, Pl217 commented on bin/test.sh
> +USAGE='Usage: test.sh [options] [-- [options]].\n Options:\n   -oc, --only-containers: only start docker containers\n    -sc, --stop-containers: stop docker containers\n    -k, --keep: keep jest runi
We can have multi-line text in shell scripts.

2024-03-19 20:34 UTC, Pl217 commented on bin/test.sh
> +if [ $STOP_CONTAINERS -eq 1 ]; then
I am getting an error here: `./bin/test.sh: line 49: [: : integer expression expected`

2024-03-19 20:34 UTC, Pl217 commented on tests/resolvers/software-info.spec.ts
> +    const softwareInfo = data.softwareInfo[0];
We can remove usage of `any` and use [optional chaining operator (`?.`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).
```suggestion
    const data = response.data;
    expect(data?.softwareInfo).toBeDefined();
    expect(data?.softwareInfo.length).toBeGreaterThan(0);
    const softwareInfo = data?.softwareInfo[0];
```

2024-03-19 20:34 UTC, Pl217 commented on tests/resolvers/software-info.spec.ts
The test cases in this file are pretty repetitive and you can extract the code into a common method.

2024-03-19 20:34 UTC, Pl217 commented on tests/docker-compose.yml
We need to update this file for Compose V2 - HPC-9088

2024-03-19 20:34 UTC, Pl217 commented on tests/testContext.ts
> +  transactions: Record<string, Knex.Transaction>;
The transactions aren't used anywhere, so we can just remove the property.
```suggestion
```

2024-03-19 20:38 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2024-03-20 09:37 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2024-03-20 12:08 UTC, unocha-hpc approved these changes
Checks have passed and this pull request is ready for manual review

2024-03-20 12:09 UTC, Pl217 approved these changes
Me and @manelcecs have agreed to remove Solr from test containers.

2024-03-20 12:18 UTC, merged