Updated the docker-compose.yml to include redis for ratelimiting
UN-OCHA/hpc-api pull request #5
Opened 2021-03-31 01:36 UTC by rgautam98

This docker-compose includes the image from bitnami. We are using the latest revision. The image also supports master nodes, replication and cluster configuration. I however ignored all those right now as I believe ops team will have a better understanding of the deployment. 

Having said that, I belive in our production, it would be great to have an elastic cache cluster so that high availability and clustering can be given to a third party provider. 

If for any reason we dont have the choice, the bitnami image will do all of that for us.

2021-04-19 13:04 UTC, s0 requested changes
Good start, but I'd like to see some usage to make sure that it's all set up correctly. In this case, just a simple endpoint that checks that it can connect to redis okay, and can store and retreive some cached value.

@astroash is working on lots of changes atm, so it may not be a great time to implement this. I'll reassign to her to let us know when it makes sense to add these changes, at which point she can open it up to you to implement again.

Beyond this, using the image that serban indicated will be needed too.

2021-04-20 08:24 UTC, teodorescuserban requested changes
Postgres env var names become:
- `POSTGRES_PASSWORD` -> `PGSQL_PASS`
- `POSTGRES_USER` -> `PGSQL_USER`
- `POSTGRES_DB` -> `PGSQL_DB`

2021-04-20 08:24 UTC, teodorescuserban commented on docker-compose.yml
> +    image: bitnami/redis:6.2
```suggestion
    image: unocha/redis:6
```

2021-04-20 08:24 UTC, teodorescuserban commented on docker-compose.yml
> +      - REDIS_PASSWORD=password123 # If you login via the tty shell, use the command redis-cli -a $REDIS_PASSWORD to access the cli
```suggestion
```

2021-04-20 08:24 UTC, teodorescuserban commented on docker-compose.yml
> +      - redis_data:/bitnami/redis/data
```suggestion
      - redis_data:/var/lib/redis
```

2021-04-20 08:24 UTC, teodorescuserban commented on docker-compose.yml
>      image: postgres:12.4-alpine
```suggestion
    image: unocha/postgres:12
```

2021-04-26 11:36 UTC, astroash commented
@rgautam98 new docker configuration has been merged in https://github.com/UN-OCHA/hpc-api/pull/14 . Let me know if you want to go through any of the changes together on call :)

@teodorescuserban thanks for the pointers for getting this PR moved over to the unocha docker image

2021-12-14 08:51 UTC, Pl217 commented
This PR gained attention from various people, but author hasn't responded to any in quite a while, it's been almost 9 months since opening the PR.

If we also consider that this PR just registers Redis and doesn't do anything with it, there is no value in keeping this dead PR open, so I'm going to close it.

2021-12-14 08:51 UTC, closed without merging